name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_trimmer:
    path: ../

  cupertino_icons: ^1.0.2
  video_player: ^1.0.1
  file_picker:
    git:
      url: git://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
