name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_trimmer:
    path: ../

  cupertino_icons: ^1.0.2
  video_player: ^2.0.2
  file_picker: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
